name: Go Check Test

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  go_checks:
    name: Run Go Checks
    uses: travelaudience/ci/.github/workflows/go_checks_r.yml@main
    with:
      go_version: "1.25"
      run_static_analysis: true
      private_module_credentials_enabled: false
    secrets: inherit

  go_test_and_coverage:
    name: Run Go Tests and Coverage
    uses: travelaudience/ci/.github/workflows/go_test_and_coverage_r.yml@main
    with:
      go_version: "1.25"
      private_module_credentials_enabled: false
    secrets: inherit
